@startuml
<style>
class {
    BackgroundColor transparent
    linecolor transparent
}
</style>


hide empty members
hide circle


class "<#lightblue,#black>|= CUSTOMERNAME:string |= AVG: float|=TOTAL:float |\n\
<#white>|  2  |  55.736  |  1684115918 |" as sales {
}


@enduml
